import requests
import time

# Endpoint URL
apikey = "0UGhhKVqW1ofy0osb1dOcvabBS1vQZQHi4hKATs73an5pZY2xvv50xtnk0U"
url = f"http://127.0.0.1:8000/Stock/peerstocks/?apikey={apikey}"


tickers = [
    # "RELIANCE",
    # "TCS",
    # "HDFCBANK",
    # "BHARTIARTL",
    # "ICICIBANK",
    # "INFY",
    # "SBIN",
    # "LICI",
    # "HINDUNILVR",
    # "ITC",
    # "LT",
    # "HCLTECH",
    # "BAJFINANCE",
    # "SUNPHARMA",
    # "NTPC",
    # "MARUTI",
    # "AXISBANK",
    # "ONGC",
    # "M&M",
    # "KOTAKBANK",
    # "TATAMOTORS",
    # "ADANIENT",
    # "ULTRACEMCO",
    # "POWERGRID",
    # "HAL",
    # "TITAN",
    # "ADANIPORTS",
    # "DMART",
    # "COALINDIA",
    # "WIPRO",
    # "BAJAJ-AUTO",
    # "ASIANPAINT",
    # "BAJAJFINSV",
    # "ADANIGREEN",
    # "SIEMENS",
    # "ADANIPOWER",
    # "TRENT",
    # "NESTLEIND",
    # "JSWSTEEL",
    # "HINDZINC",
    # "IOC",
    # "BEL",
    # "IRFC",
    # "DLF",
    # "VBL",
    # "TATASTEEL",
    # "VEDL",
    # "LTIM",
    # "GRASIM",
    # "INDIGO",
    # "SBILIFE",
    # "PFC",
    # "ABB",
    # "TECHM",
    # "PIDILITIND",
    # "HINDALCO",
    # "AMBUJACEM",
    # "HDFCLIFE",
    # "RECLTD",
    # "DIVISLAB",
    # "GAIL",
    # "BPCL",
    # "TATAPOWER",
    # "GODREJCP",
    # "BRITANNIA",
    # "EICHERMOT",
    # "MOTHERSON",
    # "LODHA",
    # "BANKBARODA",
    # "CIPLA",
    # "JSWENERGY",
    # "TVSMOTOR",
    # "PNB",
    # "SHRIRAMFIN",
    # "CHOLAFIN",
    # "BAJAJHLDNG",
    # "HAVELLS",
    # "ADANIENSOL",
    # "CGPOWER",
    # "TORNTPHARM",
    # "DRREDDY",
    # "IOB",
    # "ZYDUSLIFE",
    # "TATACONSUM",
    # "UNITDSPR",
    # "RVNL",
    # "HEROMOTOCO",
    # "DABUR",
    # "ICICIPRULI",
    # "BOSCHLTD",
    # "POLYCAB",
    # "INDUSTOWER",
    # "CUMMINSIND",
    # "NAUKRI",
    # "INDHOTEL",
    # "APOLLOHOSP",
    # "MANKIND",
    # "OFSS",
    # "INDUSINDBK",
    # "ICICIGI",
    # "JINDALSTEL",
    # "SOLARINDS",
    # "CANBK",
    # "LUPIN",
    # "MAXHEALTH",
    # "SUZLON",
    # "BHEL",
    # "UNIONBANK",
    # "SHREECEM",
    # "IDBI",
    # "NHPC",
    # "HDFCAMC",
    # "MAZDOCK",
    # "OIL",
    # "COLPAL",
    # "ATGL",
    # "DIXON",
    # "MARICO",
    # "PERSISTENT",
    # "HINDPETRO",
    # "GODREJPROP",
    # "TORNTPOWER",
    # "GMRAIRPORT",
    # "AUROPHARMA",
    # "IDEA",
    # "POLICYBZR",
    # "TIINDIA",
    # "MUTHOOTFIN",
    # "INDIANB",
    # "PRESTIGE",
    # "IRCTC",
    # "SRF",
    # "YESBANK",
    # "GICRE",
    # "BHARATFORG",
    # "OBEROIRLTY",
    # "SBICARD",
    # "ASHOKLEY",
    # "ALKEM",
    # "KALYANKJIL",
    # "NMDC",
    # "PIIND",
    # "SUPREMEIND",
    # "LINDEINDIA",
    # "PATANJALI",
    # "BERGEPAINT",
    # "FACT",
    # "PHOENIXLTD",
    # "JSL",
    # "UNOMINDA",
    # "SCHAEFFLER",
    # "UCOBANK",
    # "THERMAX",
    # "BALKRISIND",
    # "VOLTAS",
    # "MRF",
    # "MPHASIS",
    # "CONCOR",
    # "ABCAPITAL",
    # "LTTS",
    # "POWERINDIA",
    # "SAIL",
    # "TATACOMM",
    # "NYKAA",
    # "UBL",
    # "PGHH",
    # "ASTRAL",
    # "IDFCFIRSTB",
    # "PETRONET",
    # "BANKINDIA",
    # "CENTRALBK",
    # "BSE",
    # "SUNDARMFIN",
    # "COROMANDEL",
    # "SJVN",
    # "COCHINSHIP",
    # "FEDERALBNK",
    # "PAGEIND",
    # "COFORGE",
    # "AUBANK",
    # "MOTILALOFS",
    # "LLOYDSME",
    # "BDL",
    # "KPITTECH",
    # "TATAELXSI",
    # "GVT&D",
    # "GLENMARK",
    # "GLAXO",
    # "ACC",
    # "FORTIS",
    # "PAYTM",
    # "AWL",
    # "NAM-INDIA",
    # "HONAUT",
    # "FLUOROCHEM",
    # "MAHABANK",
    # "BIOCON",
    # "UPL",
    # "ESCORTS",
    # "JUBLFOOD",
    # "APLAPOLLO",
    # "EXIDEIND",
    # "SONACOMS",
    # "LTF",
    # "GUJGASLTD",
    # "360ONE",
    # "3MINDIA",
    # "MFSL",
    # "KEI",
    # "AIAENG",
    # "DEEPAKNTR",
    # "NATIONALUM",
    # "BLUESTARCO",
    # "NIACL",
    # "PSB",
    # "APARINDS",
    # "AJANTPHARM",
    # "IPCALAB",
    # "LICHSGFIN",
    # "NLCINDIA",
    # "M&MFIN",
    # "IRB",
    # "CRISIL",
    # "GODREJIND",
    # "DALBHARAT",
    # "SYNGENE",
    # "ENDURANCE",
    # "METROBRAND",
    # "JKCEMENT",
    # "KAYNES",
    # "TATAINVEST",
    # "IGL",
    # "ABFRL",
    # "APOLLOTYRE",
    # "STARHEALTH",
    # "MRPL",
    # "EMAMILTD",
    # "KPRMILL",
    # "CHOLAHLDNG",
    # "SUNTV",
    # "CDSL",
    # "MANYAVAR",
    # "BANDHANBNK",
    # "GLAND",
    # "GODFRYPHLP",
    # "MEDANTA",
    # "MSUMI",
    # "BRIGADE",
    # "NBCC",
    # "HINDCOPPER",
    # "POONAWALLA",
    # "PPLPHARMA",
    # "JBCHEPHARM",
    # "DELHIVERY",
    # "GILLETTE",
    # "CARBORUNIV",
    # "ABREL",
    # "BASF",
    # "ZFCVINDIA",
    # "AEGISLOG",
    # "ITI",
    # "RADICO",
    # "SUNDRMFAST",
    # "TIMKEN",
    # "TATACHEM",
    # "CROMPTON",
    # "ISEC",
    # "SUMICHEM",
    # "LALPATHLAB",
    # "INOXWIND",
    # "HSCL",
    # "LAURUSLABS",
    # "TVSHLTD",
    # "GRINDWELL",
    # "AIIL",
    # "WHIRLPOOL",
    # "SKFINDIA",
    # "ARE&M",
    # "HATSUN",
    # "NH",
    # "NATCOPHARM",
    # "KEC",
    # "RATNAMANI",
    # "PFIZER",
    # "EIHOTEL",
    # "CESC",
    # "KIOCL",
    # "PEL",
    # "POLYMED",
    # "ANGELONE",
    # "PNBHOUSING",
    # "CASTROLIND",
    # "KANSAINER",
    # "IRCON",
    # "JWL",
    # "TRITURBINE",
    # "SHYAMMETL",
    # "ANANTRAJ",
    # "FSL",
    # "ATUL",
    # "CAMS",
    # "AFFLE",
    # "TEJASNET",
    # "FIVESTAR",
    # "APLLTD",
    # "ABSLAMC",
    # "JBMA",
    # "KAJARIACER",
    # "DEVYANI",
    # "GRSE",
    # "CYIENT",
    # "GSPL",
    # "FINCABLES",
    # "ELGIEQUIP",
    # "KIMS",
    # "KPIL",
    # "ASTERDM",
    # "RAMCOCEM",
    # "JINDALSAW",
    # "BIKAJI",
    # "AARTIIND",
    # "CIEINDIA",
    # "CHAMBLFERT",
    # "VINATIORGA",
    # "SWANENERGY",
    # "NCC",
    # "VGUARD",
    # "PTCIL",
    # "SCHNEIDER",
    # "IIFL",
    # "RELAXO",
    # "HFCL",
    # "BLUEDART",
    # "CHALET",
    # "WELCORP",
    # "BATAINDIA",
    # "TRIDENT",
    # "JYOTHYLAB",
    # "FINPIPE",
    # "TITAGARH",
    # "TECHNOE",
    # "SONATSOFTW",
    # "CREDITACC",
    # "KFINTECH",
    # "GESHIP",
    # "ERIS",
    # "AMBER",
    # "KARURVYSYA",
    # "CENTURYPLY",
    # "KIRLOSENG",
    # "JAIBALAJI",
    # "IFCI",
    # "ASTRAZEN",
    # "LMW",
    # "BBTC",
    # "BEML",
    # "BSOFT",
    # "RKFORGE",
    # "DCMSHRIRAM",
    # "NAVINFLUOR",
    # "WOCKPHARMA",
    # "ASAHIINDIA",
    # "CGCL",
    # "ZENSARTECH",
    # "IEX",
    # "HBLENGINE",
    # "NEWGEN",
    # "APTUS",
    # "SOBHA",
    # "ANANDRATHI",
    # "BLS",
    # "JUBLPHARMA",
    # "WELSPUNLIV",
    # "TTML",
    # "NEULANDLAB",
    # "INDIAMART",
    # "PCBL",
    # "ACE",
    # "AKZOINDIA",
    # "MGL",
    # "KIRLOSBROS",
    # "PGEL",
    # "CLEAN",
    # "FINEORG",
    # "GRINFRA",
    # "ZENTEC",
    # "RITES",
    # "REDINGTON",
    # "KSB",
    # "UTIAMC",
    # "SANOFI",
    # "SPLPETRO",
    # "DATAPATTNS",
    # "NSLNISP",
    # "GODREJAGRO",
    # "PVRINOX",
    # "RPOWER",
    # "EIDPARRY",
    # "CAPLIPOINT",
    # "GRAVITA",
    # "RAILTEL",
    # "VTL",
    # "ECLERX",
    # "GRANULES",
    # "SWSOLAR",
    # "RAINBOW",
    # "NAVA",
    # "ELECON",
    # "GPIL",
    # "SARDAEN",
    # "PRAJIND",
    # "AAVAS",
    # "DEEPAKFERT",
    # "INGERRAND",
    # "OLECTRA",
    # "ZYDUSWELL",
    # "MMTC",
    # "CRAFTSMAN",
    # "IWEL",
    # "ZEEL",
    # "WESTLIFE",
    # "LTFOODS",
    # "JPPOWER",
    # "MINDACORP",
    # "CUB",
    # "INTELLECT",
    # "NUVOCO",
    # "RAYMOND",
    # "CHENNPETRO",
    # "VOLTAMP",
    # "TARIL",
    # "TTKPRESTIG",
    # "GENUSPOWER",
    # "ALOKINDS",
    # "RBLBANK",
    # "ENGINERSIN",
    # "RHIM",
    # "MARKSANS",
    # "HAPPSTMNDS",
    # "TEGA",
    # "AETHER",
    # "JMFINANCIL",
    # "SAFARI",
    # "CEATLTD",
    # "SCI",
    # "GMDCLTD",
    # "J&KBANK",
    # "MAHSCOOTER",
    # "USHAMART",
    # "TANLA",
    # "STAR",
    # "ELECTCAST",
    # "CANFINHOME",
    # "BALRAMCHIN",
    # "JUBLINGREA",
    # "EUREKAFORB",
    # "JSWHL",
    # "MAPMYINDIA",
    # "INDIACEM",
    # "KPIGREEN",
    # "METROPOLIS",
    # "JKTYRE",
    # "CERA",
    # "ALKYLAMINE",
    # "VESUVIUS",
    # "QUESS",
    # "PRUDENT",
    # "BAJAJELEC",
    # "GRAPHITE",
    # "PNCINFRA",
    # "LEMONTREE",
    # "SAPPHIRE",
    # "NETWORK18",
    # "ISGEC",
    # "GALAXYSURF",
    # "RCF",
    # "RTNINDIA",
    # "SYMPHONY",
    # "PURVA",
    # "GPPL",
    # "BIRLACORPN",
    # "SAREGAMA",
    # "BECTORFOOD",
    # "ARVIND",
    # "THOMASCOOK",
    # "SFL",
    # "RELINFRA",
    # "LATENTVIEW",
    # "EDELWEISS",
    # "HOMEFIRST",
    # "FORCEMOT",
    # "JUSTDIAL",
    # "ROUTE",
    # "HGINFRA",
    # "IONEXCHANG",
    # "RENUKA",
    # "VIJAYA",
    # "SAMMAANCAP",
    # "JKLAKSHMI",
    # "ESABINDIA",
    # "GNFC",
    # "TIPSMUSIC",
    # "WABAG",
    # "TRIVENI",
    # "KNRCON",
    # "IIFLCAPS",
    # "POWERMECH",
    # "CHOICEIN",
    # "KIRLPNU",
    # "AURIONPRO",
    # "CCL",
    # "SHAKTIPUMP",
    # "PRSMJOHNSN",
    # "TEXRAIL",
    # "CAMPUS",
    # "ITDCEM",
    # "SHRIPISTON",
    # "TIMETECHNO",
    # "MASTEK",
    # "LLOYDSENGG",
    # "BBOX",
    # "RATEGAIN",
    # "GSFC",
    # "CMSINFO",
    # "RUSTOMJEE",
    # "VARROC",
    # "PGHL",
    # "MAHSEAMLES",
    # "HEG",
    # "RELIGARE",
    # "AVANTIFEED",
    # "ACI",
    # "EQUITASBNK",
    # "SYRMA",
    # "STARCEMENT",
    # "GRWRHITECH",
    # "SANSERA",
    # "FDC",
    # "MEDPLUS",
    # "GALLANTT",
    # "KTKBANK",
    # "MAHLIFE",
    # "TCI",
    # "GANESHHOUC",
    # "ANURAS",
    # "GMRP&UI",
    # "SUNTECK",
    # "EMBDL",
    # "RTNPOWER",
    # "MHRIL",
    # "RAJESHEXPO",
    # "GARFIBRES",
    # "EPIGRAL",
    # "JKPAPER",
    # "SHOPERSTOP",
    # "INFIBEAM",
    # "EPL",
    # "MOIL",
    # "ASTRAMICRO",
    # "CHEMPLASTS",
    # "SANDUMA",
    # "AHLUCONT",
    # "EMIL",
    # "DIACABS",
    # "TV18BRDCST",
    # "UJJIVANSFB",
    # "SHILPAMED",
    # "PARADEEP",
    # "ETHOSLTD",
    # "ICIL",
    # "VMART",
    # "LXCHEM",
    # "WELENT",
    # "HCC",
    # "DBL",
    # "MIDHANI",
    # "PDSL",
    # "MANINFRA",
    # "IFBIND",
    # "DHANUKA",
    # "TMB",
    # "ORCHPHARMA",
    # "NAZARA",
    # "RESPONIND",
    # "EMUDHRA",
    # "ARVINDFASN",
    # "DODLA",
    # "SUNDARMHLD",
    # "BALUFORGE",
    # "TIIL",
    # "INDIGOPNTS",
    # "SUPRAJIT",
    # "BALAMINES",
    # "GREENLAM",
    # "SPARC",
    # "JINDWORLD",
    # "SUDARSCHEM",
    # "GABRIEL",
    # "ASHOKA",
    # "VIPIND",
    # "SURYAROSNI",
    # "KRBL",
    # "GOKEX",
    # "SHARDAMOTR",
    # "NESCO",
    # "KESORAMIND",
    # "HNDFDS",
    # "ORIENTCEM",
    # "SOUTHBANK",
    # "TARC",
    # "BORORENEW",
    # "TDPOWERSYS",
    # "EASEMYTRIP",
    # "RALLIS",
    # "PRIVISCL",
    # "JAICORPLTD",
    # "VSTIND",
    # "NFL",
    # "STLTECH",
    # "ICRA",
    # "PILANIINVS",
    # "ROLEXRINGS",
    # "AVL",
    # "GOCOLORS",
    # "UEL",
    # "GULFOILLUB",
    # "LUXIND",
    # "PCJEWELLER",
    # "GMMPFAUDLR",
    # "GAEL",
    # "SHAREINDIA",
    # "AGI",
    # "LLOYDSENT",
    # "PRINCEPIPE",
    # "PRICOLLTD",
    # "GHCL",
    # "ALLCARGO",
    # "JKIL",
    # "ITDC",
    # "TI",
    # "HCG",
    # "DBCORP",
    # "SIS",
    # "GUJALKALI",
    # "RSYSTEMS",
    # "PTC",
    # "SHARDACROP",
    # "INOXGREEN",
    # "AARTIPHARM",
    # "RAIN",
    # "CSBBANK",
    # "THANGAMAYL",
    # "BANCOINDIA",
    # "JCHAC",
    # "HEMIPROP",
    # "MTARTECH",
    # "NPST",
    # "ORIENTELEC",
    # "MANORAMA",
    # "MSTCLTD",
    # "PAISALO",
    # "KIRLOSIND",
    # "OPTIEMUS",
    # "ANUP",
    # "BBL",
    # "DYNAMATECH",
    # "MASFIN",
    # "HEIDELBERG",
    # "HERITGFOOD",
    # "VAIBHAVGBL",
    # "KSCL",
    # "TEAMLEASE",
    # "CARTRADE",
    # "RBA",
    # "NEOGEN",
    # "SKIPPER",
    # "GANECOS",
    # "VRLLOG",
    # "BOROLTD",
    # "REFEX",
    # "E2E",
    # "WONDERLA",
    # "ADVENZYMES",
    # "BHARATRAS",
    # "SHAILY",
    # "BAJAJHIND",
    # "UNICHEMLAB",
    # "ORISSAMINE",
    # "PATELENG",
    # "HARSHA",
    # "NOCIL",
    # "GATEWAY",
    # "ROSSARI",
    # "JAMNAAUTO",
    # "SUPRIYA",
    # "AARTIDRUGS",
    # "WEBELSOLAR",
    # "JISLJALEQS",
    # "THYROCARE",
    # "PITTIENG",
    # "PGIL",
    # "RAMKY",
    # "JTEKTINDIA",
    # "STYRENIX",
    # "HIKAL",
    # "UFLEX",
    # "PARAS",
    # "GREENPANEL",
    # "SHANTIGEAR",
    # "SUBROS",
    # "BOMDYEING",
    # "JAYNECOIND",
    # "GREENPLY",
    # "BALMLAWRIE",
    # "IMAGICAA",
    # "SEQUENT",
    # "BANARISUG",
    # "BHAGCHEM",
    # "GREAVESCOT",
    # "AVALON",
    # "LGBBROSLTD",
    # "AVANTEL",
    # "SKYGOLD",
    # "PFOCUS",
    # "SUNFLAG",
    # "FCL",
    # "MOREPENLAB",
    # "VENUSPIPES",
    # "V2RETAIL",
    # "GUFICBIO",
    # "JTLIND",
    # "FIEMIND",
    # "CIGNITITEC",
    # "WSTCSTPAPR",
    # "IMFA",
    # "TCIEXP",
    # "KKCL",
    # "KPEL",
    # "GOKULAGRO",
    # "SOTL",
    # "SULA",
    # "DCBBANK",
    # "DCXINDIA",
    # "VSTTILLERS",
    # "INDIAGLYCO",
    # "KSL",
    # "DHANI",
    # "KDDL",
    # "VEEDOL",
    # "SEPC",
    # "ARTEMISMED",
    # "LUMAXTECH",
    # "POLYPLEX",
    # "SWARAJENG",
    # "HONDAPOWER",
    # "KINGFA",
    # "LAOPALA",
    # "ARVSMART",
    # "HGS",
    # "STYLAMIND",
    # "HMT",
    # "MPSLTD",
    # "INDRAMEDCO",
    # "RPGLIFE",
    # "SANGHVIMOV",
    # "BEPL",
    # "JINDALPOLY",
    # "DATAMATICS",
    # "HPL",
    # "DALMIASUG",
    # "ALEMBICLTD",
    # "HATHWAY",
    # "CARERATING",
    # "SHK",
    # "SBCL",
    # "MTNL",
    # "SEAMECLTD",
    # "INDOSTAR",
    # "SERVOTECH",
    # "ASHIANA",
    # "SANDHAR",
    # "GIPCL",
    # "DPABHUSHAN",
    # "SINDHUTRAD",
    # "BAJAJCON",
    # "SSWL",
    # "QUICKHEAL",
    # "NUCLEUS",
    # "DELTACORP",
    # "NAVNETEDUL",
    # "TIRUMALCHM",
    # "BFUTILITIE",
    # "MAHLOG",
    # "RPSGVENT",
    # "GENSOL",
    # "GOLDIAM",
    # "MARINE",
    # "PRAKASH",
    # "GEOJITFSL",
    # "GOODLUCK",
    # "MAITHANALL",
    # "KITEX",
    # "SJS",
    # "PRECWIRE",
    # "GTLINFRA",
    # "DCAL",
    # "TVSSRICHAK",
    # "PFS",
    # "SAKSOFT",
    # "APOLLO",
    # "CAPACITE",
    # "REPCOHOME",
    # "MARATHON",
    # "INDOCO",
    # "KCP",
    # "ASHAPURMIN",
    # "WENDT",
    # "GENESYS",
    # "JASH",
    # "POKARNA",
    # "ADFFOODS",
    # "EVEREADY",
    # "SALASAR",
    # "FINOPB",
    # "SAGCEM",
    # "NSIL",
    # "TASTYBITE",
    # "RPEL",
    # "HINDOILEXP",
    # "SUVEN",
    # "KOLTEPATIL",
    # "PREMEXPLN",
    # "SPECTRUM",
    # "NRBBEARING",
    # "DOLLAR",
    # "ORIENTHOT",
    # "SOMANYCERA",
    # "FOSECOIND",
    # "VADILALIND",
    # "AJMERA",
    # "HITECH",
    # "AUTOAXLES",
    # "GLOBUSSPR",
    # "GEPIL",
    # "TCPLPACK",
    # "NILKAMAL",
    # "SUMMITSEC",
    # "RAJRATAN",
    # "DREDGECORP",
    # "VISHNU",
    # "FUSION",
    # "THEJO",
    # "SHALBY",
    # "DEEPINDS",
    # "VENKEYS",
    # "HLEGLAS",
    # "KICL",
    # "VINDHYATEL",
    # "FILATEX",
    # "SIYSIL",
    # "MONARCH",
    # "MAYURUNIQ",
    # "MMFL",
    # "UNITECH",
    # "HUHTAMAKI",
    # "RANEHOLDIN",
    # "SMLISUZU",
    # "VAKRANGEE",
    # "SASKEN",
    # "HINDWAREAP",
    # "PSPPROJECT", a
    # "KRSNAA",
    # "CONFIPET",
    # "XPROINDIA",
    # "LANDMARK",
    # "STOVEKRAFT",
    # "SOLARA",
    # "DCW",
    # "SABTNL",
    # "JYOTISTRUC",
    # "ACCELYA",
    # "EIHAHOTELS",
    # "PENIND",
    # "SMSPHARMA",
    # "DOLATALGO",
    # "DISHTV",
    # "MANGLMCEM",
    # "BFINVEST",
    # "PRECAM",
    # "IOLCP",
    # "MOLDTKPAC",
    # "RAMRAT",
    # "LUMAXIND",
    # "MANINDS",
    # "INSECTICID",
    # "MOL",
    # "THEMISMED",
    # "DREAMFOLKS",
    # "PIXTRANS",
    # "PARACABLES",
    # "DOLPHIN",
    # "INDOTECH",
    # "TARSONS",
    # "DEN",
    # "KMEW",
    # "PANAMAPET",
    # "NELCO",
    # "PARAGMILK",
    # "FMGOETZE",
    # "IPL",
    # "NITINSPIN",
    # "APOLLOPIPE",
    # "63MOONS",
    # "DIAMONDYD",
    # "AXISCADES",
    # "UGROCAP",
    # "ASTEC",
    # "RUPA",
    # "CUPID",
    # "UNIVCABLES",
    # "TATVA",
    # "SPAL",
    # "CENTUM",
    # "CARYSIL",
    # "BARBEQUE",
    # "VSSL",
    # "GREENPOWER",
    # "RAMCOIND",
    # "TIL",
    # "MUKANDLTD",
    # "JITFINFRA",
    # "SANGHIIND",
    # "NIITLTD",
    # "TTKHLTCARE",
    # "POCL",
    # "OMAXE",
    # "PNBGILTS",
    # "KIRIINDUS",
    # "YASHO",
    # "COSMOFIRST",
    # "APCOTEXIND",
    # "SDBL",
    # "HESTERBIO",
    # "IGARASHI",
    # "HUBTOWN",
    # "ANDHRAPAP",
    # "CANTABIL",
    # "GOCLCORP",
    # "UNIPARTS",
    # "SBGLP",
    # "NAVKARCORP",
    # "SESHAPAPER",
    # "BLKASHYAP",
    # "DLINKINDIA",
    # "SATIN",
    # "IFGLEXPOR",
    # "EKC",
    # "ALICON",
    # "SANGAMIND",
    # "TAJGVK",
    # "TALBROAUTO",
    # "MICEL",
    # "EXPLEOSOL",
    # "VERANDA",
    # "AWHCL",
    # "JAGRAN",
    # "DIVGIITTS",
    # "JINDRILL",
    # "HARIOMPIPE",
    # "MBAPL",
    # "SHRIRAMPPS",
    # "VERTOZ",
    # "MASTERTR",
    # "WINDLAS",
    # "JPASSOCIAT",
    # "GMBREW",
    # "UDAICEMENT",
    # "WEL",
    # "STERTOOLS",
    # "WHEELS",
    # "RAMASTEEL",
    # "BSHSL",
    # "GPTINFRA",
    # "SIRCA",
    # "GKWLIMITED",
    # "CAMLINFINE",
    # "IGPL",
    # "SALZERELEC",
    # "GRPLTD",
    # "ROTO",
    # "SYNCOMF",
    # "SIGACHI",
    # "DPSCLTD",
    # "MUFIN",
    # "HERANBA",
    # "EXCELINDUS",
    # "GNA",
    # "SUYOG",
    # "SURYODAY",
    # "RIIL",
    # "ATULAUTO",
    # "GTPL",
    # "SADHNANIQ",
    # "PANACEABIO",
    # "AGARIND",
    # "DSSL",
    # "BIGBLOC",
    # "HIRECT",
    # "SWELECTES",
    # "DCMSRIND",
    # "BCG",
    # "WALCHANNAG",
    # "BHARATWIRE",
    # "PENINLAND",
    # "INDNIPPON",
    # "KOKUYOCMLN",
    # "ARMANFIN",
    # "MADRASFERT",
    # "ZOTA",
    # "SPIC",
    # "OAL",
    # "NDRAUTO",
    # "HIMATSEIDE",
    # "HITECHGEAR",
    # "OMINFRAL",
    # "TEXINFRA",
    # "AMNPLST",
    # "MANGCHEFER",
    # "DYCL",
    # "BCLIND",
    # "RML",
    # "MSPL",
    # "ASALCBR",
    # "EVERESTIND",
    # "MONTECARLO",
    # "TFCILTD",
    # "ALLDIGI",
    # "BUTTERFLY",
    # "EIMCOELECO",
    # "SMCGLOBAL",
    # "5PAISA",
    # "MATRIMONY",
    "YUKEN",
    "IMPAL",
    "LIKHITHA",
    "KABRAEXTRU",
    "SUBEXLTD",
    "FAIRCHEMOR",
    "SPORTKING",
    "TBZ",
    "STEELCAS",
    "WINDMACHIN",
    "CENTRUM",
    "VINCOFE",
    "ARIHANTSUP",
    "DVL",
    "CLSEL",
    "HEXATRADEX",
    "TNPL",
    "RICOAUTO",
    "RAMCOSYS",
    "SHANKARA",
    "PUNJABCHEM",
    "ASIANENE",
    "ANDHRSUGAR",
    "KRISHANA",
    "AGIIL",
    "KELLTONTEC",
    "ACLGATI",
    "CENTENKA",
    "VIMTALABS",
    "KAMDHENU",
    "BESTAGRO",
    "ADSL",
    "SHREDIGCEM",
    "KERNEX",
    "LINCOLN",
    "SPCENET",
    "WEALTH",
    "ONEPOINT",
    "MACPOWER",
    "HERCULES",
    "VHL",
    "TVTODAY",
    "MANALIPETC",
    "BLISSGVS",
    "ESTER",
    "CHEMFAB",
    "GRMOVER",
    "SAURASHCEM",
    "RGL",
    "SPMLINFRA",
    "DHAMPURSUG",
    "NGLFINE",
    "XCHANGING",
    "KECL",
    "CREST",
    "KOPRAN",
    "SELAN",
    "AVADHSUGAR",
    "HLVLTD",
    "AVTNPL",
    "RAJRILTD",
    "PPL",
    "VLSFINANCE",
    "DWARKESH",
    "SNOWMAN",
    "PDMJEPAPER",
    "GULPOLY",
    "JAGSNPHARM",
    "INDOAMIN",
    "SANDESH",
    "ASAL",
    "CONTROLPR",
    "ELECTHERM",
    "SIMPLEXINF",
    "OSWALGREEN",
    "STEELXIND",
    "KUANTUM",
    "GICHSGFIN",
    "UTTAMSUGAR",
    "ICEMAKE",
    "HEUBACHIND",
    "RADHIKAJWE",
    "NDTV",
    "KSOLVES",
    "ARROWGREEN",
    "DHUNINV",
    "MAXIND",
    "PAKKA",
    "ROSSELLIND",
    "CREATIVE",
    "KOTHARIPET",
    "APTECHT",
    "INDORAMA",
    "HARDWYN",
    "NACLIND",
    "SRHHYPOLTD",
    "NELCAST",
    "UNIENTER",
    "SATIA",
    "MUNJALAU",
    "FAZE3Q",
    "ANUHPHR",
    "BAJAJHCARE",
    "MAGADSUGAR",
    "BLAL",
    "ELIN",
    "SHALPAINTS",
    "JAYBARMARU",
    "GANESHBE",
    "DHARMAJ",
    "AGSTRA",
    "SUTLEJTEX",
    "NAHARSPING",
    "VALIANTORG",
    "ZEEMEDIA",
    "ZUARIIND",
    "INFOBEAN",
    "URJA",
    "STCINDIA",
    "GANDHITUBE",
    "THEINVEST",
    "KAMOPAINTS",
    "KRITI",
    "ARIHANTCAP",
    "NINSYS",
    "AYMSYNTEX",
    "NCLIND",
    "ENIL",
    "RSWM",
    "ASIANTILES",
    "ORIENTPPR",
    "BODALCHEM",
    "DHANBANK",
    "BIRLAMONEY",
    "INNOVANA",
    "GVKPIL",
    "SICALLOG",
    "SHIVALIK",
    "AMBIKCO",
    "GFLLIMITED",
    "LINC",
    "PRIMESECU",
    "20MICRONS",
    "RUSHIL",
    "SBC",
    "RACLGEAR",
    "RITCO",
    "MINDTECK",
    "CHEMCON",
    "SARVESHWAR",
    "FILATFASH",
    "ZODIAC",
    "SILVERTUC",
    "CSLFINANCE",
    "ESSARSHPNG",
    "MALLCOM",
    "TRACXN",
    "VHLTD",
    "STEL",
    "VISAKAIND",
    "JAYAGROGN",
    "OSWALAGRO",
    "UGARSUGAR",
    "ELDEHSG",
    "JPOLYINVST",
    "ZUARI",
    "DBOL",
    "BHAGERIA",
    "DECCANCE",
    "MMP",
    "ONWARDTEC",
    "RUBYMILLS",
    "FOODSIN",
    "JINDALPHOT",
    "RADIANTCMS",
    "ONMOBILE",
    "REPRO",
    "COFFEEDAY",
    "SHREEPUSHK",
    "GEECEE",
    "GSLSU",
    "SAKUMA",
    "HPAL",
    "SUKHJITS",
    "MAANALU",
    "GLOSTERLTD",
    "LIBERTSHOE",
    "SPENCERS",
    "NECLIFE",
    "ACL",
    "TPLPLASTEH",
    "SARLAPOLY",
    "WSI",
    "FOCUS",
    "TNPETRO",
    "CHEVIOT",
    "TRANSWORLD",
    "CHEMBOND",
    "RBL",
    "HINDCOMPOS",
    "SPECIALITY",
    "DENORA",
    "SURAJLTD",
    "DIGISPICE",
    "APEX",
    "ALBERTDAVD",
    "SCHAND",
    "NDL",
    "PARSVNATH",
    "WANBURY",
    "VIKASLIFE",
    "CCCL",
    "BIL",
    "INDSWFTLAB",
    "DMCC",
    "KHAICHEM",
    "PVP",
    "AFFORDABLE",
    "PLASTIBLEN",
    "BIRLACABLE",
    "RPPINFRA",
    "EMAMIPAP",
    "INDOTHAI",
    "NRL",
    "TVSELECT",
    "MENONBE",
    "NITCO",
    "VINYLINDIA",
    "LOKESHMACH",
    "ASHIMASYN",
    "BALAJITELE",
    "BEDMUTHA",
    "HMVL",
    "SAKAR",
    "LGHL",
    "GOACARBON",
    "KHADIM",
    "CONSOFINVT",
    "MBLINFRA",
    "NAHARPOLY",
    "NRAIL",
    "KRITINUT",
    "DONEAR",
    "RSSOFTWARE",
    "ADVANIHOTR",
    "SKMEGGPROD",
    "SILINV",
    "CYBERTECH",
    "IRIS",
    "MOLDTECH",
    "RACE",
    "BCONCEPTS",
    "ALANKIT",
    "SREEL",
    "IITL",
    "INDOBORAX",
    "NBIFIN",
    "MUNJALSHOW",
    "NAGAFERT",
    "IZMO",
    "REMSONSIND",
    "DPWIRES",
    "VIKASECO",
    "PAVNAIND",
    "AVG",
    "DICIND",
    "TARACHAND",
    "MANAKSIA",
    "FCSSOFT",
    "GENUSPAPER",
    "MEDICAMEQ",
    "ASMS",
    "SGIL",
    "KAYA",
    "PRECOT",
    "ORIENTCER",
    "AURUM",
    "EMKAY",
    "XTGLOBAL",
    "MIRZAINT",
    "AARTISURF",
    "HINDMOTORS",
    "ORICONENT",
    "HTMEDIA",
    "BPL",
    "KAMATHOTEL",
    "PTL",
    "RCOM",
    "CLEDUCATE",
    "MUTHOOTCAP",
    "HCL-INSYS",
    "KCPSUGIND",
    "INDOUS",
    "KANORICHEM",
    "PREMIERPOL",
    "SHIVAMAUTO",
    "INTLCONV",
    "IRISDOREME",
    "MODISONLTD",
    "BALAXI",
    "3IINFOLTD",
    "NAHARCAP",
    "MAZDA",
    "ZIMLAB",
    "KILITCH",
    "GEEKAYWIRE",
    "DIAMINESQ",
    "SINCLAIR",
    "AXITA",
    "ASAHISONG",
    "MIRCELECTR",
    "TRF",
    "IFBAGRO",
    "UYFINCORP",
    "APCL",
    "SADBHAV",
    "SRD",
    "TEMBO",
    "ORIENTBELL",
    "MANAKCOAT",
    "NILAINFRA",
    "INSPIRISYS",
    "GOKUL",
    "BANSWRAS",
    "ALMONDZ",
    "ELGIRUBCO",
    "UNIDT",
    "KOTHARIPRO",
    "RADIOCITY",
    "ORBTEXP",
    "MEGASOFT",
    "IL&FSENGG",
    "LYKALABS",
    "SOFTTECH",
    "SRGHFL",
    "AUTOIND",
    "DYNPRO",
    "KAPSTON",
    "UFO",
    "DCI",
    "HARRMALAYA",
    "NILASPACES",
    "VARDHACRLC",
    "BBTCL",
    "EIFFL",
    "VENUSREM",
    "VIPULLTD",
    "SHEMAROO",
    "SEJALLTD",
    "JETAIRWAYS",
    "SHREERAMA",
    "KOTARISUG",
    "APOLSINHOT",
    "KRITIKA",
    "PRITIKAUTO",
    "SAKHTISUG",
    "MAWANASUG",
    "AIRAN",
    "HITECHCORP",
    "PODDARMENT",
    "NIPPOBATRY",
    "MANORG",
    "PASUPTAC",
    "S&SPOWER",
    "ATLANTAA",
    "PROZONER",
    "MGEL",
    "DJML",
    "CINELINE",
    "DCMNVL",
    "MANOMAY",
    "SCPL",
    "BRNL",
    "PONNIERODE",
    "ABAN",
    "EMAMIREAL",
    "EXXARO",
    "ABINFRA",
    "NATHBIOGEN",
    "RUCHIRA",
    "MANAKSTEEL",
    "TIRUPATIFL",
    "UCAL",
    "UNIVPHOTO",
    "OSIAHYPER",
    "SINTERCOM",
    "LAL",
    "ESSENTIA",
    "TRU",
    "SIGMA",
    "SAHYADRI",
    "MEDICO",
    "GLOBALVECT",
    "SUMIT",
    "IVC",
    "JAYSREETEA",
    "GLOBAL",
    "GUJAPOLLO",
    "ARIES",
    "SMSLIFE",
    "ASIANHOTNR",
    "TRIGYN",
    "VIPCLOTHNG",
    "BYKE",
    "NDLVENTURE",
    "MKPL",
    "SUNDRMBRAK",
    "GULFPETRO",
    "MAHEPC",
    "VARDMNPOLY",
    "BASML",
    "SHREYANIND",
    "UMAEXPORTS",
    "STARPAPER",
    "CCHHL",
    "LORDSCHLO",
    "DRCSYSTEMS",
    "RHL",
    "BGRENERGY",
    "GOLDTECH",
    "RAMAPHO",
    "REPL",
    "SOUTHWEST",
    "SHYAMCENT",
    "COASTCORP",
    "KMSUGAR",
    "RVHL",
    "BROOKS",
    "WELINV",
    "RANASUG",
    "INTENTECH",
    "MURUDCERA",
    "MCLEODRUSS",
    "USK",
    "BHAGYANGR",
    "VISASTEEL",
    "ZODIACLOTH",
    "SHRADHA",
    "VISHWARAJ",
    "A2ZINFRA",
    "RANEENGINE",
    "PILITA",
    "RAJTV",
    "DEVIT",
    "SVLL",
    "MARALOVER",
    "NECCLTD",
    "RUCHINFRA",
    "INDOWIND",
    "VIRINCHI",
    "SURANAT&P",
    "RAJMET",
    "PAR",
    "AARON",
    "MEGASTAR",
    "LANCORHOL",
    "MODIRUBBER",
    "MAGNUM",
    "NURECA",
    "ZEELEARN",
    "RAMANEWS",
    "PPAP",
    "MAHASTEEL",
    "RPPL",
    "LGBFORGE",
    "TTL",
    "THOMASCOTT",
    "CROWN",
    "VETO",
    "RKEC",
    "MANCREDIT",
    "COMSYN",
    "CORDSCABLE",
    "NOIDATOLL",
    "TAKE",
    "OMAXAUTO",
    "SUPREMEINF",
    "STARTECK",
    "ALPHAGEO",
    "SHIVATEX",
    "DTIL",
    "DELPHIFX",
    "OCCL",
    "DUCON",
    "SONAMLTD",
    "GINNIFILA",
    "AHLEAST",
    "UNITEDPOLY",
    "INDTERRAIN",
    "KANPRPLA",
    "INVENTURE",
    "AKSHARCHEM",
    "NITIRAJ",
    "HINDCON",
    "SMARTLINK",
    "PRAXIS",
    "EQUIPPP",
    "PANSARI",
    "DGCONTENT",
    "GENCON",
    "PRAENG",
    "UNIVASTU",
    "LOYALTEX",
    "PANACHE",
    "SUPERHOUSE",
    "SMLT",
    "TIPSFILMS",
    "COMPUSOFT",
    "JMA",
    "SADBHIN",
    "ARCHIDPLY",
    "ANIKINDS",
    "BSL",
    "ISFT",
    "UMANGDAIRY",
    "NIRAJ",
    "MAHAPEXLTD",
    "OSWALSEEDS",
    "SAH",
    "RAJSREESUG",
    "OILCOUNTUB",
    "ALPA",
    "TAINWALCHM",
    "SURANASOL",
    "EMMBI",
    "AARTECH",
    "ASPINWALL",
    "SHAH",
    "UNITEDTEA",
    "AMJLAND",
    "LAGNAM",
    "IVP",
    "CORALFINAC",
    "SIGIND",
    "CAPTRUST",
    "INCREDIBLE",
    "HINDNATGLS",
    "GTL",
    "INDBANK",
    "WORTH",
    "LOVABLE",
    "SOMICONVEY",
    "AARVI",
    "GILLANDERS",
    "TEXMOPIPES",
    "GVPTECH",
    "CTE",
    "SALSTEEL",
    "WEIZMANIND",
    "IL&FSTRANS",
    "GSS",
    "BAGFILMS",
    "CENTEXT",
    "BALPHARMA",
    "DHRUV",
    "KALYANIFRG",
    "ARVEE",
    "MANAKALUCO",
    "JHS",
    "PRITI",
    "MHLXMIRU",
    "FLEXITUFF",
    "BAFNAPH",
    "HDIL",
    "AIROLAM",
    "MAHESHWARI",
    "KREBSBIO",
    "VAISHALI",
    "BAIDFIN",
    "XELPMOC",
    "MANGALAM",
    "KEYFINSERV",
    "GANGESSECU",
    "HILTON",
    "MUKTAARTS",
    "RHFL",
    "DCM",
    "JOCIL",
    "LAMBODHARA",
    "SIL",
    "ATAM",
    "SELMC",
    "SIKKO",
    "ANMOL",
    "SHEKHAWATI",
    "TARMAT",
    "SPLIL",
    "SETCO",
    "EROSMEDIA",
    "AKI",
    "LATTEYS",
    "REGENCERAM",
    "BHANDARI",
    "RELCHEMQ",
    "ANSALAPI",
    "INDIANCARD",
    "MITCON",
    "TOUCHWOOD",
    "WIPL",
    "KAKATCEM",
    "HPIL",
    "SURYALAXMI",
    "DBSTOCKBRO",
    "BHARATGEAR",
    "PATINTLOG",
    "BEARDSELL",
    "ARTNIRMAN",
    "AKSHOPTFBR",
    "ZENITHEXPO",
    "PRAKASHSTL",
    "KOHINOOR",
    "SALONA",
    "AAREYDRUGS",
    "PKTEA",
    "GAYAPROJ",
    "VISESHINFO",
    "3RDROCK",
    "AVROIND",
    "PALASHSECU",
    "AAATECH",
    "STEELCITY",
    "PIONEEREMB",
    "VASWANI",
    "TOTAL",
    "LOTUSEYE",
    "AUSOMENT",
    "TFL",
    "GLOBE",
    "LPDC",
    "SHAHALLOYS",
    "SEMAC",
    "TPHQ",
    "FIBERWEB",
    "FRETAIL",
    "MOTOGENFIN",
    "ZENITHSTL",
    "GOYALALUM",
    "SUNDARAM",
    "SOMATEX",
    "AHLADA",
    "TERASOFT",
    "EXCEL",
    "SAMPANN",
    "LASA",
    "AJOONI",
    "AMDIND",
    "BVCL",
    "FCONSUMER",
    "AARVEEDEN",
    "BANKA",
    "INDSWFTLTD",
    "SKIL",
    "GROBTEA",
    "TIMESGTY",
    "ENERGYDEV",
    "ALKALI",
    "YAARI",
    "VINNY",
    "AAKASH",
    "PALREDTEC",
    "NAGREEKEXP",
    "OBCL",
    "SECURKLOUD",
    "CEREBRAINT",
    "HECPROJECT",
    "TOKYOPLAST",
    "PARASPETRO",
    "SUVIDHAA",
    "DANGEE",
    "SAMBHAAV",
    "CINEVISTA",
    "BIOFILCHEM",
    "ARSHIYA",
    "ORIENTLTD",
    "DAMODARIND",
    "SECMARK",
    "21STCENMGM",
    "MOKSH",
    "LCCINFOTEC",
    "DELTAMAGNT",
    "ASTRON",
    "DIGJAMLMTD",
    "BLBLIMITED",
    "HISARMETAL",
    "SIMBHALS",
    "GANGAFORGE",
    "MEP",
    "ATALREAL",
    "DIL",
    "MADHUCON",
    "HBSL",
    "PNC",
    "HOVS",
    "CELEBRITY",
    "ARCHIES",
    "AGROPHOS",
    "KARMAENG",
    "LEXUS",
    "TREEHOUSE",
    "AKSHAR",
    "AROGRANITE",
    "SVPGLOB",
    "RELIABLE",
    "NIBL",
    "SHIVAMILLS",
    "BALKRISHNA",
    "ROML",
    "MBECL",
    "BANG",
    "MALUPAPER",
    "SITINET",
    "BANARBEADS",
    "WEWIN",
    "MARSHALL",
    "KEEPLEARN",
    "JETFREIGHT",
    "SEYAIND",
    "FMNL",
    "SILGO",
    "GOLDENTOBC",
    "LFIC",
    "MANUGRAPH",
    "ORIENTALTL",
    "RKDL",
    "SUPREMEENG",
    "DNAMEDIA",
    "ROLLT",
    "AKG",
    "JAIPURKURT",
    "BURNPUR",
    "GODHA",
    "ROLTA",
    "ABMINTLLTD",
    "TVVISION",
    "AKASH",
    "PEARLPOLY",
    "SUPERSPIN",
    "LAXMICOT",
    "KANANIIND",
    "GTECJAINX",
    "ASHOKAMET",
    "ADL",
    "KSHITIJPOL",
    "ANKITMETAL",
    "VINEETLAB",
    "COUNCODOS",
    "SRPL",
    "TECHIN",
    "NEXTMEDIA",
    "SHRENIK",
    "NGIL",
    "PODDARHOUS",
    "AMBICAAGAR",
    "SGL",
    "TNTELE",
    "SAGARDEEP",
    "ADROITINFO",
    "MADHAV",
    "FLFL",
    "LIBAS",
    "KHANDSE",
    "TGBHOTELS",
    "MASKINVEST",
    "ATLASCYCLE",
    "GATECH",
    "ARSSINFRA",
    "KRIDHANINF",
    "KHAITANLTD",
    "CYBERMEDIA",
    "MOHITIND",
    "SANGINITA",
    "VIJIFIN",
    "MORARJEE",
    "SUMEETINDS",
    "WILLAMAGOR",
    "UNIINFO",
    "MITTAL",
    "HYBRIDFIN",
    "HAVISHA",
    "TIJARIA",
    "NAGREEKCAP",
    "BLUECHIP",
    "FEL",
    "SANWARIA",
    "GOENKA",
    "INFOMEDIA",
    "ACEINTEG",
    "NKIND",
    "SUULD",
    "KAUSHALYA",
    "GAYAHWS",
    "VIVIDHA",
    "CALSOFT",
    "IMPEXFERRO",
    "HEADSUP",
    "EDUCOMP",
    "GUJRAFFIA",
    "WINSOME",
    "COMPINFO",
    "ANTGRAPHIC",
    "GFSTEELS",
    "MTEDUCARE",
    "SECURCRED",
    "ONELIFECAP",
    "SILLYMONKS",
    "LYPSAGEMS",
    "BOHRAIND",
    "RADAAN",
    "GLFL",
    "SHYAMTEL",
    "NORBTEAEXP",
    "UMESLTD",
    "NTL",
    "SHANTI",
    "TCIFINANCE",
    "OMKARCHEM",
    "ORTINGLOBE",
    "VCL",
    "DCMFINSERV",
    "CREATIVEYE",
    "BLUECOAST",
    "PREMIER",
    "UNIVAFOODS",
    "EUROTEXIND",
    "FSC",
    "SETUINFRA",
    "BKMINDST",
    "CMICABLES",
    "LAKPRE",
]
# Loop through and post each ticker
# for ticker in tickers:
#     payload = {"tickers": [ticker]}
#     response = requests.post(url, json=payload)

#     # Logging the result
#     print(f"Sent ticker: {ticker}, Status: {response.status_code}")
    # time.sleep(30)


import requests

API_KEY = "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"

url = "https://api.openai.com/v1/chat/completions"

headers = {
    "Authorization": f"Bearer {API_KEY}",
    "Content-Type": "application/json"
}

data = {
    "model": "gpt-4o-mini",
    "messages": [
        {"role": "system", "content": "You are a helpful assistant."},
        {"role": "user", "content": "Hello, how are you?"}
    ]
}

response = requests.post(url, headers=headers, json=data)

print(response.status_code)
print(response.json())

# "parameters": [
#   {
#     "type": "text",
#     "text": "Aman"
#   }
# ]
# 📲 It will appear as:

# Hi Aman, welcome to our platform! 🎉

# Would you like me to check your template message code and help you test it live? Just paste your current API call or template JSON.


# You said:
# {
# "apiKey": string,
# "campaignName": string,
# "destination": string,
# "userName": string,
# "source": string,
# "media": {
# "url": string,
# "filename": string
# },
# "templateParams": [
# string
# ],
# "tags": [
# string
# ],
# "attributes": {
# "attribute_name": string
# }
# }

# URL = https://backend.aisensy.com/campaign/t1/api/v2
# apikey = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODFmN2RhYjhhOTU1MGMwZWU2Njk3MiIsIm5hbWUiOiJQZW5ueXdpc2VUcmFkaW5nIiwiYXBwTmFtZSI6IkFpU2Vuc3kiLCJjbGllbnRJZCI6IjY4ODFmN2RhYjhhOTU1MGMwZWU2Njk2ZCIsImFjdGl2ZVBsYW4iOiJGUkVFX0ZPUkVWRVIiLCJpYXQiOjE3NTMzNDgwNTh9.3FlV2c4ZveHg43B-1jB8TR8ZMCQArjFkItZPyrEVzu0

# write the code to send a whatsapp message


# ChatGPT said:
# Here’s a Python script using requests to send a WhatsApp message via AiSensy’s v2 API using the payload and apiKey you provided:

# ✅ Python Code (using requests)
# python
# Copy
# Edit

# import requests

# url = "https://backend.aisensy.com/campaign/t1/api/v2"
# headers = {
#     "Content-Type": "application/json"
#     # "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODFmN2RhYjhhOTU1MGMwZWU2Njk3MiIsIm5hbWUiOiJQZW5ueXdpc2VUcmFkaW5nIiwiYXBwTmFtZSI6IkFpU2Vuc3kiLCJjbGllbnRJZCI6IjY4ODFmN2RhYjhhOTU1MGMwZWU2Njk2ZCIsImFjdGl2ZVBsYW4iOiJGUkVFX0ZPUkVWRVIiLCJpYXQiOjE3NTMzNDgwNTh9.3FlV2c4ZveHg43B-1jB8TR8ZMCQArjFkItZPyrEVzu0"
# }

# payload = {
#     "apiKey": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4ODFmN2RhYjhhOTU1MGMwZWU2Njk3MiIsIm5hbWUiOiJQZW5ueXdpc2VUcmFkaW5nIiwiYXBwTmFtZSI6IkFpU2Vuc3kiLCJjbGllbnRJZCI6IjY4ODFmN2RhYjhhOTU1MGMwZWU2Njk2ZCIsImFjdGl2ZVBsYW4iOiJGUkVFX0ZPUkVWRVIiLCJpYXQiOjE3NTMzNDgwNTh9.3FlV2c4ZveHg43B-1jB8TR8ZMCQArjFkItZPyrEVzu0",  # Leave empty, since we are using Authorization header
#     "campaignName": "TestCampaign",
#     "destination": "918118929071",  # replace with actual number with country code
#     "userName": "Aman",
#     "source": "Api",
#     "media": {
#         "url": "",  # optional, use valid media URL
#         "filename": "image.jpg"
#     },
#     "templateParams": [
#         "Aman", "Welcome!"  # depends on your approved template structure
#     ],
#     "tags": [
#         "test", "python"
#     ],
#     "attributes": {
#         "attribute_name": "attribute_value"
#     }
# }

# response = requests.post(url, json=payload, headers=headers)

# # Output response
# print("Status Code:", response.status_code)
# print("Response:", response.json())
