import requests
import time
# Endpoint URL
url = 'http://127.0.0.1:8000/Stock/peerstocks/'


tickers = [ "RBLBANK", "ENGINERSIN", "RHIM", "MARKSANS", "HAPPSTMNDS",
  "TEGA", "AETHER", "JMFINANCIL", "SAFARI", "CEATLTD", "SCI", "GMDCLTD",
  "J&KBANK", "MAHSCOOTER", "USHAMART", "STAR", "ELECTCAST", "CANFINHOME",
  "BALRAMCHIN", "JUBLINGREA", "EUREKAFORB", "MAPMYINDIA", "INDIACEM",
  "KPIGREEN", "METROPOLIS", "JKTYRE", "CERA", "ALKYLAMINE", "VESUVIUS",
  "PRUDENT", "BAJAJELEC", "GRAPHITE", "PNCINFRA", "LEMONTREE",
  "SAPPHIRE", "NETWORK18", "GALAXYSURF", "RCF", "RTNINDIA", "SYMPHONY",
  "GPPL", "BIRLACORPN", "SAREGAMA", "BECTORFOOD", "ARVIND", "THOMASCOOK",
  "SFL", "RELINFRA", "LATENTVIEW", "EDELWEISS", "HOMEFIRST", "FORCEMOT",
  "JUSTDIAL", "HGINFRA", "IONEXCHANG", "RENUKA", "VIJAYA", "SAMMAANCAP",
  "JKLAKSHMI", "ESABINDIA", "GNFC", "TIPSMUSIC", "TRIVENI", "KNRCON",
  "IIFLCAPS", "POWERMECH", "CHOICEIN", "KIRLPNU", "AURIONPRO", "CCL",
  "SHAKTIPUMP", "PRSMJOHNSN", "TEXRAIL", "CAMPUS", "ITDCEM", "SHRIPISTON",
  "TIMETECHNO", "MASTEK", "LLOYDSENGG", "BBOX", "RATEGAIN", "GSFC",
  "CMSINFO", "RUSTOMJEE", "VARROC", "PGHL", "MAHSEAMLES", "HEG",
  "RELIGARE", "AVANTIFEED", "ACI", "EQUITASBNK", "STARCEMENT",
  "GRWRHITECH", "SANSERA", "FDC", "MEDPLUS", "GALLANTT", "KTKBANK",
  "MAHLIFE", "TCI", "GANESHHOUC", "ANURAS", "GMRP&UI", "SUNTECK",
  "RTNPOWER", "RAJESHEXPO", "GARFIBRES", "EPIGRAL", "JKPAPER",
  "SHOPERSTOP", "INFIBEAM", "EPL", "MOIL", "ASTRAMICRO", "CHEMPLASTS",
  "SANDUMA", "AHLUCONT", "EMIL", "DIACABS", "TV18BRDCST", "UJJIVANSFB",
  "SHILPAMED", "PARADEEP", "ETHOSLTD", "ICIL", "LXCHEM", "WELENT", "HCC",
  "DBL", "MIDHANI", "PDSL", "MANINFRA", "IFBIND", "DHANUKA", "TMB",
  "ORCHPHARMA", "NAZARA", "RESPONIND", "EMUDHRA", "ARVINDFASN",
  "SUNDARMHLD", "BALUFORGE", "TIIL", "INDIGOPNTS", "SUPRAJIT", "BALAMINES",
  "GREENLAM", "JINDWORLD", "SUDARSCHEM", "GABRIEL", "ASHOKA", "VIPIND",
  "SURYAROSNI", "KRBL", "SHARDAMOTR", "KESORAMIND", "HNDFDS", "ORIENTCEM",
  "SOUTHBANK", "TARC", "BORORENEW", "TDPOWERSYS", "EASEMYTRIP", "RALLIS",
  "PRIVISCL", "JAICORPLTD", "VSTIND", "NFL", "STLTECH", "ICRA",
  "PILANIINVS", "ROLEXRINGS", "AVL", "GOCOLORS", "UEL", "GULFOILLUB",
  "LUXIND", "PCJEWELLER", "GMMPFAUDLR", "GAEL", "SHAREINDIA", "AGI",
  "LLOYDSENT", "PRINCEPIPE", "PRICOLLTD", "GHCL", "ALLCARGO", "JKIL",
  "ITDC", "TI", "HCG", "DBCORP", "SIS", "GUJALKALI", "RSYSTEMS", "PTC",
  "SHARDACROP", "INOXGREEN", "AARTIPHARM", "RAIN", "CSBBANK",
  "THANGAMAYL", "BANCOINDIA", "HEMIPROP", "MTARTECH", "NPST", "ORIENTELEC",
  "MANORAMA", "MSTCLTD", "PAISALO", "KIRLOSIND", "OPTIEMUS", "ANUP",
  "BBL", "DYNAMATECH", "MASFIN", "HEIDELBERG", "HERITGFOOD", "VAIBHAVGBL",
  "KSCL", "TEAMLEASE", "CARTRADE", "RBA", "NEOGEN", "SKIPPER", "GANECOS",
  "VRLLOG", "BOROLTD", "E2E", "WONDERLA", "ADVENZYMES", "BHARATRAS",
  "SHAILY", "BAJAJHIND", "UNICHEMLAB", "ORISSAMINE", "PATELENG", "HARSHA",
  "GATEWAY", "ROSSARI", "JAMNAAUTO", "SUPRIYA", "AARTIDRUGS",
  "WEBELSOLAR", "JISLJALEQS", "THYROCARE", "PITTIENG", "PGIL",
  "JTEKTINDIA", "STYRENIX", "GREENPANEL", "SHANTIGEAR", "SUBROS",
  "BOMDYEING", "JAYNECOIND", "GREENPLY", "BALMLAWRIE", "IMAGICAA",
  "SEQUENT", "BANARISUG", "BHAGCHEM", "GREAVESCOT", "AVALON",
  "LGBBROSLTD", "AVANTEL", "SKYGOLD", "PFOCUS", "SUNFLAG", "FCL",
  "MOREPENLAB", "VENUSPIPES", "V2RETAIL", "GUFICBIO", "JTLIND", "FIEMIND",
  "CIGNITITEC", "WSTCSTPAPR", "IMFA", "TCIEXP", "KKCL", "KPEL",
  "GOKULAGRO", "SOTL", "SULA", "DCBBANK", "DCXINDIA", "VSTTILLERS",
  "INDIAGLYCO", "KSL", "KDDL", "VEEDOL", "SEPC", "ARTEMISMED", "LUMAXTECH",
  "POLYPLEX", "SWARAJENG", "HONDAPOWER", "KINGFA", "LAOPALA", "ARVSMART",
  "HGS", "STYLAMIND", "HMT", "MPSLTD", "INDRAMEDCO", "RPGLIFE",
  "SANGHVIMOV", "BEPL", "JINDALPOLY", "DATAMATICS", "HPL", "DALMIASUG",
  "ALEMBICLTD", "HATHWAY", "CARERATING", "SHK", "SBCL", "MTNL",
  "SEAMECLTD", "INDOSTAR", "SERVOTECH"
]

# Loop through and post each ticker
for ticker in tickers:
    payload = {
        "tickers": [ticker]
    }
    response = requests.post(url, json=payload)

    # Logging the result
    print(f"Sent ticker: {ticker}, Status: {response.status_code}")
    time.sleep(30)