"""Expiry feild in Plan

Revision ID: 73978ada2be6
Revises: c7e5b31dbd97
Create Date: 2025-07-16 20:21:13.963882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73978ada2be6'
down_revision: Union[str, Sequence[str], None] = 'c7e5b31dbd97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Plans', sa.Column('Expiry', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Plans', 'Expiry')
    # ### end Alembic commands ###
