"""Your migration message

Revision ID: ad0ac082985d
Revises: 73978ada2be6
Create Date: 2025-07-23 09:07:21.035381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0ac082985d'
down_revision: Union[str, Sequence[str], None] = '73978ada2be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SwingPoints', sa.Column('period', sa.String(), nullable=True))
    op.create_index(op.f('ix_SwingPoints_period'), 'SwingPoints', ['period'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_SwingPoints_period'), table_name='SwingPoints')
    op.drop_column('SwingPoints', 'period')
    # ### end Alembic commands ###
