"""Created field added in Invoice Table

Revision ID: c7e5b31dbd97
Revises: a1ac1beede26
Create Date: 2025-07-15 20:05:35.920226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7e5b31dbd97'
down_revision: Union[str, Sequence[str], None] = 'a1ac1beede26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Invoices', sa.Column('created_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Invoices', 'created_at')
    # ### end Alembic commands ###
